### ISSUE TITLE
type of institutionID

### ISSUE THREAD

**Issue by bbarker** [labordynamicsinstitute/metajelo#4]
I was wondering about this:

```
<xs:element name="institutionID" type="identifierType"> </xs:element>
```

`identifierType`, in my understanding, is a rather different thing than any sort of particular ID. Am I misunderstanding this, or should this have a different type, e.g., `xs:string`?

Perhaps it is working as intended and could be described as the the type of identifier used by the institution. I didn't find this to be immediately clear from looking at `text/idcc2019-usability.tex` or other files in the repository.

**Comment by larsvilhuber** [comment]
@clagoze is best placed to answer this question about identifierType.

**Comment by clagoze** [comment]
Yes, it looks like you found a mistake!! At first glance it seems like it should be that the type should indeed be s:string and there should be an attribute of type identifierType (indicating how to interpret the string.  I will fix and update asap.

**Comment by bbarker** [comment]
Thanks @clagoze ,

What you said make sense to me but there is still one point I'm unsure of. In the new version we have:

```xml
 <xs:element name="resourceID" minOccurs="0">
   <xs:complexType>
     <xs:simpleContent>
       <xs:extension base="xs:string">
         <xs:attribute name="relatedIdentifierType" type="identifierType"
           use="required"/>
       </xs:extension>
     </xs:simpleContent>
   </xs:complexType>
 </xs:element>
```

and 

```xml
<xs:element name="institutionID">
  <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="identifierType" type="identifierType" use="required"
        />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:element>
```

This means that resource ids and institution ids are effectively the same, due to their structure and underlying reliance on `identifierType`. I have to plead ignorance in knowing what an example of an institution id would be, but looking at some of the examples I'm familiar with in `identifierType`, these seem to typically point into specific archives rather than point to specific institutions.

**Comment by larsvilhuber** [comment]
identifierType should be general enough. A DOI is an identifierType but so is FunderID, or a re3data ID (which may be a DOI). So while in practice the resourceID may not use every possible identifierType, ie there is overlap, generically, this is what we want.

--
Lars Vilhuber
on mobile device

________________________________
