### ISSUE TITLE
yesno type

### ISSUE THREAD

**Issue by bbarker** [labordynamicsinstitute/metajelo#5]
Used by e.g. `versioning`:

```
      <xs:simpleType name="yesno">
                <xs:restriction base="xs:string">
                        <xs:enumeration value="yes"/>
                        <xs:enumeration value="no"/>
                </xs:restriction>
        </xs:simpleType>
```

Could this just more simply be replaced by the builtin or presumably more standardized `xs:boolean`?

**Comment by larsvilhuber** [comment]
Sure.

--
Lars Vilhuber
on mobile device

________________________________

**Comment by larsvilhuber** [comment]
@clagoze could you modify the XSD to switch yes/no questions to boolean, or is there a concern about that?

**Comment by clagoze** [comment]
Yes, it should be boolean, will update asap
